### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by msaaksjarvi** [AlexChristensen/SemNetCleaner#10]
**Copy and paste of error from your R console**
```
Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: spellcheck.menu function of textcleaner

R, SemNetCleaner, and SemNetDictionaries versions:
 • R version: 3.6.3
 • SemNetCleaner version: 1.3.1
 • SemNetDictionaries version: 0.1.8

Operating System:
 • OS: Darwin
 • Version: 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64

```

**To Reproduce:**
- Function error occurred in: [e.g., moniker function of textcleaner]

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNA Data: [your GitHub username]** *using this template* 

**R, SemNetCleaner, and SemNetDictionaries versions:**
- R [e.g., 3.6.3]
- SemNetCleaner: [e.g., 1.2.0]
- SemNetDictionaries: [e.g., 1.1.6]

**Operating System:**
 - OS: [e.g., Windows, Mac, Linux]
 - Version [e.g., 10 x64 build 18363]

**Additional context and comments**
- [e.g., function with arguments]
- [e.g., worked before but doesn't now]
- [e.g., expected behavior]
- [e.g., other things you've tried]

**Comment by AlexChristensen** [comment]
Hi @msaaksjarvi,

Can you provide more details? Can you provide a toy example so that I can reproduce this error?

**Comment by msaaksjarvi** [comment]
I am looking at ice cream ingredients, and for some reason, the text cleaner does not like it when I try to change the word "milksugar" to milk, sugar; I've tried it twice and it crashes both times. However, if I leave the "milksugar" be as it is, I do not get an error. For other types of word combos, such as "wheatgraham", changed to wheat, graham, the error does not occur; it only occurs for "milksugar". As I am able to skip the error by leaving "milksugar" be (which I can easily do), this is more of a "nice to know" bug than a massive problem, but I still thought I'd flag it.

**Comment by AlexChristensen** [comment]
Hmm.. I don't see to be able to reproduce this error:

![image](https://user-images.githubusercontent.com/32655669/103439001-39045780-4c07-11eb-9378-9d01af236523.png)

Could you email (or attach) the data where the error is occurring (i.e., just a few rows before and after the error)?

alexpaulchristensen@gmail.com
