### ISSUE TITLE
The correct.data function of textcleaner does not work

### ISSUE THREAD

**Issue by msaaksjarvi** [AlexChristensen/SemNetCleaner#11]
**Copy and paste of error from your R console**
```
An error has occurred in the 'correct.data' function of 'textcleaner':

Error in `[<-`(`*tmp*`, i, 1:length(correct.ord), value = correct.ord) : 
  subscript out of bounds

Please open a new issue on GitHub (bug report): https://github.com/AlexChristensen/SemNetCleaner/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: correct.data function of textcleaner

R, SemNetCleaner, and SemNetDictionaries versions:
 • R version: 3.6.3
 • SemNetCleaner version: 1.3.1
 • SemNetDictionaries version: 0.1.8

Operating System:
 • OS: Darwin
 • Version: 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64
```

**To Reproduce:**
- Function error occurred in: [e.g., moniker function of textcleaner]

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNA Data: [your GitHub username]** *using this template* 

**R, SemNetCleaner, and SemNetDictionaries versions:**
- R [e.g., 3.6.3]
- SemNetCleaner: [e.g., 1.2.0]
- SemNetDictionaries: [e.g., 1.1.6]

**Operating System:**
 - OS: [e.g., Windows, Mac, Linux]
 - Version [e.g., 10 x64 build 18363]

**Additional context and comments**
- [e.g., function with arguments]
- [e.g., worked before but doesn't now]
- [e.g., expected behavior]
- [e.g., other things you've tried]

**Comment by AlexChristensen** [comment]
Hi @msaaksjarvi,

Can you provide more details? For example, what is the structure of your data (rows, columns)? Can you provide a toy example so that I can reproduce this error?

**Comment by msaaksjarvi** [comment]
The structure of the data is as follows: id, and then a list of ice cream ingredients, each in their own column. I am using the general dictionary, which I must say works beautifully: the spellchecker checks each word and allows me to add the missing word to the dictionary. The dictionary part works great: it is only when the dictionary is completed (and saved) when the error occurs so basically in this part of the instructions:

"As a final step of the spell-check process, the user will be provided with instructions to verify the automated
spell-check. Verification takes place in an Excel-like spreadsheet in a window that opens up after the
instructions. At the end of the textcleaner process, a message will print letting the user know what output
they can obtain to submit their dictionary (if you saved one) and moniker glossaries to our GitHub page:
https://github.com/AlexChristensen/SemNetDictionaries/issues/new/choose."

So I don't get the message that I am supposed to get after the textcleaner process is complete, and I do not get any output either. I would greatly appreciate it if you could look into this issue. 

A final note: What a great R package you've created!!! :) I love it!! So useful for research purposes. So a big THANK YOU for that. :)
