### ISSUE TITLE
[ERROR]: prep.spellcheck.dictionary function of textcleaner

### ISSUE THREAD

**Issue by ElizabethLint** [AlexChristensen/SemNetCleaner#12]
An error has occurred in the 'prep.spellcheck.dictionary' function of 'textcleaner':

Error in apply(data, 2, function(y) gsub("([-])|[[:punct:]]", "\\1", y)) : 
  dim(X) must have a positive length

Please open a new issue on GitHub (bug report): https://github.com/AlexChristensen/SemNetCleaner/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 Function error occurred in: prep.spellcheck.dictionary function of textcleaner

R, SemNetCleaner, and SemNetDictionaries versions:
 R version: 4.0.3
 SemNetCleaner version: 1.3.1
 SemNetDictionaries version: 0.1.8

Operating System:
 OS: Windows
 Version: 10 x64 build 16299

**Comment by AlexChristensen** [comment]
Thanks, @ElizabethLint. I will take a look at this soon.

In the meantime, could you send me a toy example of your data so I can replicate the error?

alexpaulchristensen@gmail.com
