### ISSUE TITLE
[ERROR]: Using the command singularize on "stress" outputs "str"

### ISSUE THREAD

**Issue by marcelenge** [AlexChristensen/SemNetCleaner#13]
Using the command singularize on "stress" outputs "str"

**Comment by AlexChristensen** [comment]
Hi @marcelenge,

Can I have you update to the latest GitHub version: `devtools::install_github("AlexChristensen/SemNetCleaner")`

This should resolve the issue.

Thanks,
Alex

**Comment by marcelenge** [comment]
Sorry for not getting back to you earlier. The problem has been resolved by updating to the newest version.

Thanks a lot,
Marcel
