### ISSUE TITLE
pluralize with -ion doesn’t work

### ISSUE THREAD

**Issue by and3k** [AlexChristensen/SemNetCleaner#3]
Hi!

I noticed that words ending in `-ion` won’t get a `-s` added:
 
```
> pluralize('exception')
[1] "exception"
> pluralize('observation')
[1] "observation"
```

Thanks for the great function!

Best,
Bela

**Comment by AlexChristensen** [comment]
Hi @and3k,

Thanks for pointing this out! This has been corrected in the latest upload to GitHub:

`devtools::install_github("AlexChristensen/SemNetCleaner")`

All the best,
Alex
