### ISSUE TITLE
[ERROR]: Spell-check problem

### ISSUE THREAD

**Issue by Mimack** [AlexChristensen/SemNetCleaner#4]
Hi,

I have been using the package before and it worked fine, but now I suddenly run into problems in the textcleaner function. 

**Copy and paste of error from your R console**
```
An error has occurred in the 'correct.changes' function of 'textcleaner':

Error in apply(automated[, -1] != changes[, -1], 1, function(x) { : 
  dim(X) must have a positive length
```

**To Reproduce:**
- Function error occurred in: correct.changes function of textcleaner

**R, SemNetCleaner, and SemNetDictionaries versions:**
 • R version: 4.0.3
 • SemNetCleaner version: 1.3.0
 • SemNetDictionaries version: 0.1.7

**Operating System:**
 • OS: Windows
 • Version: 10 x64 build 18363

**Additional context and comments**
- worked with previous package version but doesn't now
- I tried to not change anything in the spell-check file but it still breaks
- it seems like it is a problem with the dictionary: maybe a writing permission issue?

Best wishes.
Michaela

**Comment by AlexChristensen** [comment]
Hi @Mimack,

It appears that the `apply` function is receiving a vector as the input. I've adjusted the code to force the input as a matrix, which should take care of the issue.

Please update with the latest patch: `devtools::install_github("AlexChristensen/SemNetCleaner")`

Then, restart R/RStudio after install and run:

```
library(SemNetCleaner)

your_dataset <- textcleaner(continue = your_dataset)
```

Let me know if this solves the issue. If it does not, would you mind sending me (alexpaulchristensen@gmail.com) a .Rdata file with the object you've saved the `textcleaner` output in?

**Comment by Mimack** [comment]
Hi @AlexChristensen,

Yes this solved the issue. Thanks a lot!

Best wishes,
Michaela
