### ISSUE TITLE
[ERROR]: Object Mons Not Found

### ISSUE THREAD

**Issue by dhrice** [AlexChristensen/SemNetCleaner#7]
**Copy and paste of error from your R console**
```
Auto-correcting common misspellings and monikers...done.

An error has occured in the 'auto.spellcheck' function of 'textcleaner':

Error in paste("\nAttempting to auto-correct the remaining", length(mons),  : 
  object 'mons' not found
```

**To Reproduce:**
- Function error occurred in: auto.spellcheck function of textcleaner

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNA Data: [your GitHub username]** *using this template* 

**R, SemNetCleaner, and SemNetDictionaries versions:**
- R 4.0.2
- SemNetCleaner: 1.3.0
- SemNetDictionaries: 0.1.7

**Operating System:**
 - OS: Mac
 - Version 19.6.0

**Additional context and comments**
- Hasn't yet worked. 
- Replication data attached.

[tdm.csv.zip](https://github.com/AlexChristensen/SemNetCleaner/files/5623731/tdm.csv.zip)

**Comment by AlexChristensen** [comment]
Hi @dhrice,

Looking over your data file, I can see that you have to columns "nums" and "terms." The `textcleaner` function is not equipped to handle data in this format.

`textcleaner` is designed to be used where participants are across rows (or columns) and their corresponding responses across columns (or rows). See `head(open.animals)[,-c(1:2)]` for an example.

If you are looking for spell checking of a single vector, then I can look into making this possible.

Let me know if you have any questions.

Cheers,
Alex

**Comment by dhrice** [comment]
Thanks for the quick reply, @AlexChristensen.

I reordered the dataset into multiple columns, and am getting the same error. This is setup with 50 rows and 4 columns. I am using the same code from the example. Thanks again!

[tdm.csv.zip](https://github.com/AlexChristensen/SemNetCleaner/files/5624042/tdm.csv.zip)

**Comment by AlexChristensen** [comment]
No problem, @dhrice!

The bug should be fixed now. `textcleaner` should also work with your original dataset (with the two columns).

Because there are so many terms to check in the original dataset (>10000), the preprocessing will take a long time.

I won't be able to get to speeding this process today but I will make a new issue for an enhancement of a progress bar and parallel processing for large term lists.
