### ISSUE TITLE
Version 1.3.1 Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by dhrice** [AlexChristensen/SemNetCleaner#9]
**Copy and paste of error from your R console**
```
The 'spelling' argument was not set. Using default: 'US' English spelling

IDs refer to variable: 'ID'

Converting dictionary to 'US' spelling...Error: $ operator is invalid for atomic vectors
```

**To Reproduce:**
- Function error occurred in: Error in example

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNA Data: [your GitHub username]** *using this template* 

**R, SemNetCleaner, and SemNetDictionaries versions:**
- R 4.0.2
- SemNetCleaner: 1.3.1
- SemNetDictionaries: 0.1.7

**Operating System:**
 - OS: Mac
 - Version 19.6.0

**Additional context and comments**
- Example using toy data is producing this error. Version 1.3.0 does not produce the same error.

**Comment by AlexChristensen** [comment]
Hi @dhrice,

Can I have you update the SemNetDictionaries package?

`devtools::install_github("AlexChristensen/SemNetDictionaries")`

The UK-US English conversion dataset was just added to SemNetDictionaries 0.1.8, which I believe is the source of the issue.

Please let me know if this does not resolve the issue (running the `textcleaner` example works on my computer).

Thank you,
Alex

**Comment by dhrice** [comment]
Updated, still error. However, ran it on a different computer and it works fine there. Problem on my end.
